let TimelineData = [
  {
    id: 1,
    title: "Tata 1mg",
    link: "https://www.1mg.com/",
    location: "Software Developer Engineer 1",
    desc1: "Worked on the development of LOKI, an internal omnichannel retail logistics solution, streamlining processes to reduce order fulfillment time to 30 minutes across various hubs and minimizing manual processes.",
    desc2: "Exploring Catalyst, a new performance-focused frontend framework developed at Tata 1mg.",
    desc3: "Contributed to mweb and dweb projects in PWA within a monorepo architecture, optimized for shared code usage and development efficiency across the platform.",
    date: "July 2024 - Present",
    icon: "work",
  },
  {
    id: 2,
    title: "LongShot AI",
    link: "https://drive.google.com/file/d/1udbqfRRR8w0Bj33O0lnq8y7q2guFtfpR/view?usp=sharing",
    location: "Software Engineer Intern",
    desc1: "Took the ownership of various high ROI features such as SEO Checker, Content Planner, FactGPT, Integration server and other optimization features.",
    desc2: "Revamped login infrastructure from JavaScript to TypeScript for enhanced edge case handling and TS benefits.",
    desc3: "Worked on multiple Integratioin to streamline content transfer with other platforms, using tools like Webflow, Nango, Google Search Console, Drive etc.",
    date: "December 2023 - June 2024",
    icon: "work",
  },
  {
    id: 3,
    title: "DR. A.P.J. ABDUL KALAM TECHNICAL UNIVERSITY",
    location: "Lucknow, India",
    desc1:"B.Tech Computer Science & Engineering",
    desc2: "Grade : 7.8",
    date: "Nov 2020 - May 2024",
    icon: "school",
  },
  {
    id: 4,
    title: "Smart Indian Hackathon",
    link: "https://github.com/NyayaSetu-SIH/Dashboard",
    location: "SIH 2023 Finalist",
    desc1: "Successfully demonstrated our Nyaysetu chatbot’s features, including a voice assistant for marginalized communities and detailed legal citations.",
    desc2: "",
    date: "Dec 2023 - Dec 2023",
    icon: "school",
  },
  {
    id: 5,
    title: "LongShot AI",
    link: "https://www.longshot.ai/",
    location: "FrontEnd Developer Intern",
    desc1: "Spearheaded development using Vue.js for LongShot AI’s main website, and React.js and Node.js for various other key development projects",
    desc2: "Achieved a 30% increase in user engagement by significantly improving app performance through JavaScript response streaming in AI generations and complex frontend features, including pagination, fingerprinting, and unload event.",
    date: "June 2023 - Oct 2023",
    icon: "work",
  },
  {
    id: 6,
    title: "Programming Club, AKGEC",
    link: "https://pcakgec.tech/",
    location: "Senior Coordinator",
    desc1: "Managed a team of 40+ members to conduct various technical activities, doubt sessions and coding competitions.",
    desc2: "Conducted a series of Data Structure and Algorithm workshops, and mentored hundreds of juniors.",
    date: "May 2022 - May 2024",
    icon: "work",
  },
  // {
  //   id: 3,
  //   title: "GeeksforGeeks",
  //   location: "Noida, India",
  //   desc1: "Campus Ambassador",
  //   desc2:"",
  //   date: "June 2021 - Apr 2022",
  //   icon: "work",
  // },
  {
    id: 7,
    title: "Radiant Academy",
    location: "Noida, India",
    desc1:"High School - 12th (PCM + Computer Science)",
    desc2:"Percentage : 90%",
    date: "2019",
    icon: "school",
  },
  {
    id: 8,
    title: "Radiant Academy",
    location: "Noida, India",
    desc1: "Secondary School - 10th",
    desc2:"Grade : 9.2",
    date: "2017",
    icon: "school",
  },
];

export default TimelineData;