let TimelineData = [
  {
    id: 1,
    title: "Programming Club",
    location: "AKGEC, Ghaziabad",
    desc1: "Working hand-in-hand with other club members to promote the programming culture in the college",
    desc2:"",
    date: "Apr 2022 - Present",
    icon: "work",
  },
  {
    id: 3,
    title: "GeeksforGeeks",
    location: "Noida, India",
    desc1: "Campus Ambassador",
    desc2:"",
    date: "June 2021 - Apr 2022",
    icon: "work",
  },
  {
    id: 4,
    title: "Ajay Kumar Garg Engineering College",
    location: "Ghaziabad, India",
    desc1:"Bachelors in Computer Science and Engineering. ",
    desc2: "Grade : 8.54",
    date: "December 2020 - present",
    icon: "school",
  },
  {
    id: 5,
    title: "Radiant Academy",
    location: "Noida, India",
    desc1:"Higher Secondary School, CBSE.",
    desc2:"Percentage : 90% (PCM)",
    buttonText: "College Projects",
    date: "2017 - 2019",
    icon: "school",
  },
  {
    id: 6,
    title: "Radiant Academy",
    location: "Noida, India",
    desc1: "Highschool, CBSE.",
    desc2:"Grade : 9.2",
    date: "2015 - 2017",
    icon: "school",
  },
];

export default TimelineData;