let TimelineData = [
  {
    id: 1,
    title: "Tata 1mg",
    link: "https://www.1mg.com/",
    location: "Software Engineer",
    desc1: "Architected a Webview Interface to render React pages within native apps with native-like performance. Enabled Over-the-Air (OTA) updates and rapid A/B Testing, bypassing 2-week App Store reviews to deliver features in minutes.",
    desc2: "Back-End Scale & Reliability: Engineered a high-throughput Bulk Notification Service using Apache Kafka, leveraging Consumer Groups and Semaphores to manage concurrency for massive Cloud Messaging volumes.",
    desc3: "Database Optimization: Slashed database load by 40% by consolidating 9 individual endpoints into a single aggregated query using efficient SQL GROUP BY and composite indexing.",
    desc4: "Real-time System Architecture: Designed end-to-end Pusher (WebSockets) integration to replace expensive polling. Implemented Page Visibility API logic to suspend data syncing on inactive tabs, reducing unnecessary server load by ~30% while achieving sub-second synchronization.",
    desc5: "Integrated Native-JS Bridge for secure 2-way data exchange (Auth tokens, RiderId) between web/native layers. Implemented Deep-linking logic to route users precisely to internal app states from external campaigns.",
    desc6: "Core Maintainer (Frontend Infrastructure): Established engineering standards and introduced strict TypeScript compliance/code review protocols, minimizing technical debt across the Monorepo and reducing production bugs.",
    desc7: "",
    date: "July 2024 - Present",
    icon: "work",
  },
  {
    id: 1.5,
    title: "Goxec",
    link: "https://github.com/dontdude/goxec",
    location: "Distributed Remote Code Execution Engine",
    desc1: "Architected a fault-tolerant Distributed System in Go, achieving <500ms cold-start latency via Docker-out-of-Docker (DooD) socket mounting (outperforming nested virtualization).",
    desc2: "Guaranteed Zero Job Loss during worker failures by implementing Redis Streams Consumer Groups, utilizing the Pending Entry List (PEL) for automatic crash recovery.",
    desc3: "Reduced deployment artifact size by 96% (800MB → 30MB) by utilizing Multi-Stage Docker Builds and Go Static Compilation on Alpine Linux.",
    desc4: "Engineered a real-time event pipeline using WebSockets (sub-50ms latency) and implemented Page Visibility API logic to suspend synchronization on inactive tabs, reducing server load by ~30%.",
    date: "Dec 2025 - Present",
    icon: "work",
  },
  {
    id: 2,
    title: "LongShot AI",
    link: "https://www.longshot.ai/",
    location: "Software Engineer Intern",
    desc1: "Modernized Authentication Infrastructure: Migrated Login flow to strict TypeScript, eliminating runtime type errors and reducing auth-related regressions by 25%. Hardened edge-case handling for enterprise clients.",
    desc2: "Core Chatbot Integrations: Developed complex UI modules and integration middleware for the core Chatbot, synchronizing content with platforms like Webflow & Drive for enterprise clients.",
    desc3: "High-Scale UX Performance: Implemented JS Fetch Streams to handle AI response streaming for 200k+ global users, reducing perceived latency by showing content generation in real-time.",
    date: "July 2023 - June 2024",
    icon: "work",
  },
  {
    id: 3,
    title: "DR. A.P.J. ABDUL KALAM TECHNICAL UNIVERSITY",
    location: "Lucknow, India",
    desc1:"Bachelor of Technology in Computer Science",
    desc2: "Grade : 8",
    date: "2020 - 2024",
    icon: "school",
  },
  {
    id: 4,
    title: "Smart India Hackathon",
    link: "https://github.com/NyayaSetu-SIH/Dashboard",
    location: "Finalist - SIH 2023 (NyaySetu)",
    desc1: "Multilingual voice conversational AI assistant: Built real-time Speech-to-Text (STT) and Text-to-Speech (TTS) pipelines to enable seamless bidirectional audio interaction.",
    desc2: "Impact: Secured National Finalist position in Smart India Hackathon 2023 for improving legal accessibility.",
    date: "Oct 2023 - Dec 2023",
    icon: "school",
  },
  {
    id: 6,
    title: "Programming Club, AKGEC",
    link: "https://pcakgec.tech/",
    location: "Senior Coordinator",
    desc1: "Managed a team of 40+ members to conduct various technical activities, doubt sessions and coding competitions.",
    desc2: "Conducted a series of Data Structure and Algorithm workshops, and mentored hundreds of juniors.",
    date: "May 2022 - May 2024",
    icon: "school",
  },
];

export default TimelineData;